set(_CATKIN_CURRENT_PACKAGE "gps")
set(gps_VERSION "0.1.0")
set(gps_MAINTAINER "edxian <edxian@todo.todo>")
set(gps_PACKAGE_FORMAT "2")
set(gps_BUILD_DEPENDS "roscpp")
set(gps_BUILD_EXPORT_DEPENDS "roscpp")
set(gps_BUILDTOOL_DEPENDS "catkin")
set(gps_BUILDTOOL_EXPORT_DEPENDS )
set(gps_EXEC_DEPENDS "roscpp")
set(gps_RUN_DEPENDS "roscpp")
set(gps_TEST_DEPENDS )
set(gps_DOC_DEPENDS )
set(gps_URL_WEBSITE "")
set(gps_URL_BUGTRACKER "")
set(gps_URL_REPOSITORY "")
set(gps_DEPRECATED "")