# CMake generated Testfile for 
# Source directory: /home/andrew/NCRL/AprilTag_Localization/src
# Build directory: /home/andrew/NCRL/AprilTag_Localization/src/yaml_service
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("gtest")
subdirs("Env/husky/husky_desktop")
subdirs("Env/husky/husky_simulator")
subdirs("Env/multirotor_geometry_control/mav_comm/mav_comm")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_description")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_simulator")
subdirs("Env/husky/husky_msgs")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_comm")
subdirs("Env/multirotor_geometry_control/mav_comm/mav_msgs")
subdirs("Env/multirotor_geometry_control/gps")
subdirs("Env/multirotor_geometry_control/offb")
subdirs("Env/multirotor_geometry_control/plotmap")
subdirs("Env/multirotor_geometry_control/plottest")
subdirs("Env/husky/husky_control")
subdirs("Env/husky/husky_description")
subdirs("Env/husky/husky_gazebo")
subdirs("Env/husky/husky_navigation")
subdirs("Env/husky/husky_viz")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_evaluation")
subdirs("Env/multirotor_geometry_control/mav_comm/mav_planning_msgs")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_control")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_joy_interface")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rqt_rotors")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_hil_interface")
subdirs("Env/apriltag_ros/apriltag_ros")
subdirs("Env/multirotor_geometry_control/path_planner")
subdirs("realsense_gazebo_plugin")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_gazebo_plugins")
subdirs("Env/multirotor_geometry_control/rotors_simulator/rotors_gazebo")
