// Generated by gencpp from file yaml_service/readTagPos.msg
// DO NOT EDIT!


#ifndef YAML_SERVICE_MESSAGE_READTAGPOS_H
#define YAML_SERVICE_MESSAGE_READTAGPOS_H

#include <ros/service_traits.h>


#include <yaml_service/readTagPosRequest.h>
#include <yaml_service/readTagPosResponse.h>


namespace yaml_service
{

struct readTagPos
{

typedef readTagPosRequest Request;
typedef readTagPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct readTagPos
} // namespace yaml_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yaml_service::readTagPos > {
  static const char* value()
  {
    return "764aca2dfd32df67158193ad05a67c51";
  }

  static const char* value(const ::yaml_service::readTagPos&) { return value(); }
};

template<>
struct DataType< ::yaml_service::readTagPos > {
  static const char* value()
  {
    return "yaml_service/readTagPos";
  }

  static const char* value(const ::yaml_service::readTagPos&) { return value(); }
};


// service_traits::MD5Sum< ::yaml_service::readTagPosRequest> should match
// service_traits::MD5Sum< ::yaml_service::readTagPos >
template<>
struct MD5Sum< ::yaml_service::readTagPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yaml_service::readTagPos >::value();
  }
  static const char* value(const ::yaml_service::readTagPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yaml_service::readTagPosRequest> should match
// service_traits::DataType< ::yaml_service::readTagPos >
template<>
struct DataType< ::yaml_service::readTagPosRequest>
{
  static const char* value()
  {
    return DataType< ::yaml_service::readTagPos >::value();
  }
  static const char* value(const ::yaml_service::readTagPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yaml_service::readTagPosResponse> should match
// service_traits::MD5Sum< ::yaml_service::readTagPos >
template<>
struct MD5Sum< ::yaml_service::readTagPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yaml_service::readTagPos >::value();
  }
  static const char* value(const ::yaml_service::readTagPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yaml_service::readTagPosResponse> should match
// service_traits::DataType< ::yaml_service::readTagPos >
template<>
struct DataType< ::yaml_service::readTagPosResponse>
{
  static const char* value()
  {
    return DataType< ::yaml_service::readTagPos >::value();
  }
  static const char* value(const ::yaml_service::readTagPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YAML_SERVICE_MESSAGE_READTAGPOS_H
