// Generated by gencpp from file yaml_service/readTagPosRequest.msg
// DO NOT EDIT!


#ifndef YAML_SERVICE_MESSAGE_READTAGPOSREQUEST_H
#define YAML_SERVICE_MESSAGE_READTAGPOSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yaml_service
{
template <class ContainerAllocator>
struct readTagPosRequest_
{
  typedef readTagPosRequest_<ContainerAllocator> Type;

  readTagPosRequest_()
    : id(0)  {
    }
  readTagPosRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::yaml_service::readTagPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yaml_service::readTagPosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct readTagPosRequest_

typedef ::yaml_service::readTagPosRequest_<std::allocator<void> > readTagPosRequest;

typedef boost::shared_ptr< ::yaml_service::readTagPosRequest > readTagPosRequestPtr;
typedef boost::shared_ptr< ::yaml_service::readTagPosRequest const> readTagPosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yaml_service::readTagPosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yaml_service::readTagPosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yaml_service::readTagPosRequest_<ContainerAllocator1> & lhs, const ::yaml_service::readTagPosRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yaml_service::readTagPosRequest_<ContainerAllocator1> & lhs, const ::yaml_service::readTagPosRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yaml_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yaml_service::readTagPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yaml_service::readTagPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yaml_service::readTagPosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef7df1d34137d3879d089ad803388efa";
  }

  static const char* value(const ::yaml_service::readTagPosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef7df1d34137d387ULL;
  static const uint64_t static_value2 = 0x9d089ad803388efaULL;
};

template<class ContainerAllocator>
struct DataType< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yaml_service/readTagPosRequest";
  }

  static const char* value(const ::yaml_service::readTagPosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
;
  }

  static const char* value(const ::yaml_service::readTagPosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct readTagPosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yaml_service::readTagPosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yaml_service::readTagPosRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YAML_SERVICE_MESSAGE_READTAGPOSREQUEST_H
