// Generated by gencpp from file yaml_service/readTagPosResponse.msg
// DO NOT EDIT!


#ifndef YAML_SERVICE_MESSAGE_READTAGPOSRESPONSE_H
#define YAML_SERVICE_MESSAGE_READTAGPOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yaml_service
{
template <class ContainerAllocator>
struct readTagPosResponse_
{
  typedef readTagPosResponse_<ContainerAllocator> Type;

  readTagPosResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  readTagPosResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::yaml_service::readTagPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yaml_service::readTagPosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct readTagPosResponse_

typedef ::yaml_service::readTagPosResponse_<std::allocator<void> > readTagPosResponse;

typedef boost::shared_ptr< ::yaml_service::readTagPosResponse > readTagPosResponsePtr;
typedef boost::shared_ptr< ::yaml_service::readTagPosResponse const> readTagPosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yaml_service::readTagPosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yaml_service::readTagPosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yaml_service::readTagPosResponse_<ContainerAllocator1> & lhs, const ::yaml_service::readTagPosResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yaml_service::readTagPosResponse_<ContainerAllocator1> & lhs, const ::yaml_service::readTagPosResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yaml_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yaml_service::readTagPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yaml_service::readTagPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yaml_service::readTagPosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::yaml_service::readTagPosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yaml_service/readTagPosResponse";
  }

  static const char* value(const ::yaml_service::readTagPosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
;
  }

  static const char* value(const ::yaml_service::readTagPosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct readTagPosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yaml_service::readTagPosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yaml_service::readTagPosResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YAML_SERVICE_MESSAGE_READTAGPOSRESPONSE_H
